### ISSUE TITLE
Postgres integrity errors

### ISSUE THREAD

**Issue by amitofs** [getsentry/freight#54]
Encountering the same issue as: https://github.com/getsentry/freight/issues/52 while running the current master.

```
>> Running ['git', 'fetch', '--all', '-p']
Fetching origin
Raven is not configured (logging is disabled). Please see the documentation for more information.
[2015-12-08 22:41:23,950: WARNING/Worker-2] Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/srv/freight/releases/609f306b8d413505c0ab5a68168d55f8390b524d/freight/freight/tasks/execute_task.py", line 118, in run
    self._run()
  File "/srv/freight/releases/609f306b8d413505c0ab5a68168d55f8390b524d/freight/freight/tasks/execute_task.py", line 143, in _run
    self.save_chunk(result[:newline_pos])
  File "/srv/freight/releases/609f306b8d413505c0ab5a68168d55f8390b524d/freight/freight/tasks/execute_task.py", line 110, in save_chunk
    db.session.commit()
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2015, in flush
    self._flush(objects)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2133, in _flush
    transaction.rollback(_capture_exception=True)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2097, in _flush
    flush_context.execute()
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 785, in _emit_insert_statements
    execute(statement, params)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/srv/freight/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "unq_logchunk_source_offset"
DETAIL:  Key (task_id, "offset")=(8, 0) already exists.
 [SQL: 'INSERT INTO logchunk (task_id, "offset", size, text, date_created) VALUES (%(task_id)s, %(offset)s, %(size)s, %(text)s, %(date_created)s) RETURNING logchunk.id'] [parameters: {'date_created': datetime.datetime(2015, 12, 8, 22, 41, 23, 949021), 'text': u"Raven is not configured (logging is disabled). Please see the documentation for more information.\n>> Running ['git', 'fetch', '--all', '-p']\nFetching origin\nRaven is not configured (logging is disabled). Please see the documentation for more information.\n", 'offset': 0, 'task_id': 8, 'size': 255}]
[2015-12-08 22:43:33,367: WARNING/Worker-2] Raven is not configured (logging is disabled). Please see the documentation for more information.
```

**Comment by amitofs** [comment]
Symptom of https://github.com/getsentry/freight/issues/55
